### ISSUE TITLE
Ratio element as generated content

### ISSUE THREAD

**Issue by niksy** [suitcss/components-flex-embed#14]
Is there a reason why `FlexEmbed-ratio` couldn’t be generated element from `FlexEmbed` root element, and ratio values are set as modifiers on `FlexEmbed` root element?

**Comment by simonsmith** [comment]
It used to be that way, but was less flexible. See [this commit](https://github.com/suitcss/components-flex-embed/commit/61667941c11f8acec5c2d61b6c2f25e832c94f9c) for more info.

**Comment by niksy** [comment]
Ah, yes. Got it. I actually have the case where I need to have inline ratio and silly of me to not consider this in the first place :D
